### ISSUE TITLE
Fix: Not selecting any file when importing crashes Gordon

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [EOS-Solutions/Gordon#131]
# 🐛 Bug Report

When using "Import Configuration", but then cancelling the file dialog and not importing anything, Gordon crashes.
````
Object reference not set to an instance of an object.
   at Gordon.Views.Apps.Feeds.Import() in D:\a\1\s\Gordon.WebApp\Views\Apps\Feeds.Actions.cs:line 55
   at BlazorGenerator.Utils.ReflectionUtilites.InvokeAction(MethodInfo Method, Object target, Object[] KnownParams)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.FluentUI.AspNetCore.Components.FluentButton.OnClickHandlerAsync(MouseEventArgs e) in /_/src/Core/Components/Button/FluentButton.razor.cs:line 222
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
````

## 💻 Repro

1. Use "Import Configuration"
2. Click "Cancel"
3. 💥

## 🤔 Expected Behavior

Gordon does not crash.

## 😯 Current Behavior

Gordon crashes.

## Product
- [x] Gordon (Version: 1.1.26)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Stefano-Primo-EOS** [comment]
1.1.29 incoming
