### ISSUE TITLE
Fix: Updating error Gordon install 

### ISSUE THREAD

**Issue by maik13** [EOS-Solutions/Gordon#152]
# 🐛 Bug Report

Errore when updating gordon installer

gordon installer log
2024-10-24T08:31:02.6656360+02:00	INFO	[Eos.Installer.Common.PackageInstaller]	[0]	Downloading deployer from https://eospublictoolsstorage.blob.core.windows.net/installer/deployer.zip (attempt 2)
2024-10-24T08:31:02.8930953+02:00	FAIL	[Eos.Installer.Common.PackageInstaller]	[0]	Attempt '2' failed. Waiting 5secSystem.IO.IOException: The process cannot access the file 'C:\Users\mportanova\AppData\Local\EOS Solutions\InstallerData\Deployer\deployer.zip' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileInfo.Create()
   at Eos.Installer.Common.PackageInstaller.DownloadDeployer(RetryContext`1 ctx, String sourceUri, Int32 attempt) in D:\azpagent\_work\258\s\Eos.Installer.Core\PackageInstaller.cs:line 56
   at Eos.Installer.Common.PackageInstaller.DownloadDeployer(RetryContext`1 ctx, String sourceUri, Int32 attempt) in D:\azpagent\_work\258\s\Eos.Installer.Core\PackageInstaller.cs:line 67
   at Eos.Installer.Common.RetryContext`1.Run(Func`3 action) in D:\azpagent\_work\258\s\Eos.Installer.Core\RetryContext.cs:line 35

## Product
- [ ] EOS Gordon Installer (Version: 0.0.114.0)

**Comment by Stefano-Primo-EOS** [comment]
There is a strange bug on EOS Gordon Installer, in version 0.0.114. 
Can you download a newer version from the Gordon Website? 
https://eos-solutions.github.io/Gordon/

Let me know if fix the error

**Comment by maik13** [comment]
Thank you! update completed
