### ISSUE TITLE
Gordon on customer server

### ISSUE THREAD

**Issue by Chiara-Visentin-EOS** [EOS-Solutions/Gordon#46]
**Describe the bug**
I have this error, clicking on Services, in Server List.

Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione. (localhost:9462)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Bare.WebApi.Client.RestClient.GetResponse()
at Bare.WebApi.Client.RestClient.GetJsonResponse[T](https://github.com/EOS-Solutions/Gordon/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)
at Bare.WebApi.Client.ServicesApi.GetAllServices()
at Eos.Gordon.Core.Models.ServiceHost.GetServices()
at Gordon.WebApp.Views.Service.Services.LoadData() in D:\azpagent_work\264\s\Gordon.WebApp\Views\Service\Services.cs:line 42
at BlazorGenerator.Components.Base.BlazorGeneratorComponentBase.OnInitializedAsync()
at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Inner Exception
Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

**To Reproduce**

**Expected behavior**

**Screenshots**
![Img1](https://github.com/EOS-Solutions/Gordon/assets/144961606/606a0607-eb4a-4c08-9392-80b5096364d3)
![Img2](https://github.com/EOS-Solutions/Gordon/assets/144961606/3c012dde-e955-41f5-840a-95453a8b8bec)

**Product**
- [x] Gordon WebApp (Version: 1.0.137.0)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [x] Bare.WebApi (Version: 3.0.13)

**Comment by f4n0** [comment]
Have you installed Bare.WebApi on the localmachine ?

**Comment by Chiara-Visentin-EOS** [comment]
Yes,

![image](https://github.com/EOS-Solutions/Gordon/assets/144961606/9220f35e-cf07-4ef0-8e4d-92f255bac0cb)
