### ISSUE TITLE
Gordon si chiude appena viene aperto

### ISSUE THREAD

**Issue by DanieleMonti** [EOS-Solutions/Gordon#94]
Buongiorno
installando i due programmi evidenziati

Ho installato sia con utente amministratore del server che come utente amministratore di dominio ma il risultato non cambia.
vedi immagine allegata
 
All'apertura di Gordon l'applicazione si chiude immediatamente e la segnalazione nel registro di windows è quella sotto riportata.

 
Come posso risolvere?

SEGNALAZIONE

 

 
Nome registro: Application
Origine:       Windows Error Reporting
Data:          02/08/2024 12:27:21
ID evento:     1001
Categoria attività:Nessuna
Livello:       Informazioni
Parole chiave: Classico
Utente:        N/D
Computer:      Serverdev.main.lan
Descrizione:
Bucket errato 1745904464875718299, tipo 4
Nome evento: APPCRASH
Risposta: Non disponibile
ID CAB: 0

 
Firma problema:
P1: Gordon.Wpf.exe
P2: 1.1.0.0
P3: 666b0000
P4: KERNELBASE.dll
P5: 10.0.20348.2582
P6: f8072450
P7: e0434352
P8: 000000000003f14c
P9:
P10:

 
File allegati:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ecf2542a-8d94-478d-95c0-111fc66d3cb2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f2a45dd3-1dd2-4a61-93a1-2146890c30f6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2e4c56db-f3cf-420a-bb6b-a5fad10073eb.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.09996e35-d4fc-427d-b73a-c21940df6101.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7698e35a-d8ac-4a48-9d31-275926358212.tmp.txt

 
I file potrebbero essere disponibili qui:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Gordon.Wpf.exe_8a4c524a8e0227d1f009afb224857d42fd53f_4878f695_5758fe84-e51c-40dd-819f-3b3d02b22641

 
Simbolo analisi:
Nuova ricerca di soluzioni: 0
ID rapporto: c391544d-aa54-4981-8894-ec9403270aa3
Stato rapporto: 268435456
Bucket con hash: 1bcdf052508d6537883ab2dc50af869b
GUID CAB: 0
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-02T10:27:21.7470119Z" />
    <EventRecordID>21172</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Serverdev.main.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1745904464875718299</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Non disponibile</Data>
    <Data>0</Data>
    <Data>Gordon.Wpf.exe</Data>
    <Data>1.1.0.0</Data>
    <Data>666b0000</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.20348.2582</Data>
    <Data>f8072450</Data>
    <Data>e0434352</Data>
    <Data>000000000003f14c</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ecf2542a-8d94-478d-95c0-111fc66d3cb2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f2a45dd3-1dd2-4a61-93a1-2146890c30f6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2e4c56db-f3cf-420a-bb6b-a5fad10073eb.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.09996e35-d4fc-427d-b73a-c21940df6101.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7698e35a-d8ac-4a48-9d31-275926358212.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Gordon.Wpf.exe_8a4c524a8e0227d1f009afb224857d42fd53f_4878f695_5758fe84-e51c-40dd-819f-3b3d02b22641</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>c391544d-aa54-4981-8894-ec9403270aa3</Data>
    <Data>268435456</Data>
    <Data>1bcdf052508d6537883ab2dc50af869b</Data>
    <Data>0</Data>
  </EventData>
</Event>

 
Nome registro: Application
Origine:       Application Error
Data:          02/08/2024 12:27:19
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      Serverdev.main.lan
Descrizione:
Nome dell'applicazione che ha generato l'errore: Gordon.Wpf.exe, versione: 1.1.0.0, timestamp: 0x666b0000
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.20348.2582, timestamp: 0xf8072450
Codice eccezione: 0xe0434352
Offset errore 0x000000000003f14c
ID processo che ha generato l'errore: 0x3650
Ora di avvio dell'applicazione che ha generato l'errore: 0x01dae4c689bfcbfd
Percorso dell'applicazione che ha generato l'errore: C:\Users\administrator.MAIN\AppData\Local\Programs\EOS Solutions\gordon\Current\Gordon.Wpf.exe
Percorso del modulo che ha generato l'errore: C:\Windows\System32\KERNELBASE.dll
ID segnalazione: c391544d-aa54-4981-8894-ec9403270aa3
Nome completo pacchetto che ha generato l'errore:
ID applicazione relativo al pacchetto che ha generato l'errore:
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-02T10:27:19.2566699Z" />
    <EventRecordID>21171</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Serverdev.main.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Gordon.Wpf.exe</Data>
    <Data>1.1.0.0</Data>
    <Data>666b0000</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.20348.2582</Data>
    <Data>f8072450</Data>
    <Data>e0434352</Data>
    <Data>000000000003f14c</Data>
    <Data>3650</Data>
    <Data>01dae4c689bfcbfd</Data>
    <Data>C:\Users\administrator.MAIN\AppData\Local\Programs\EOS Solutions\gordon\Current\Gordon.Wpf.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>c391544d-aa54-4981-8894-ec9403270aa3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

 
Nome registro: Application
Origine:       .NET Runtime
Data:          02/08/2024 12:27:19
ID evento:     1026
Categoria attività:Nessuna
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      Serverdev.main.lan
Descrizione:
Application: Gordon.Wpf.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Impossibile trovare il file specificato. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Gordon.Wpf.App.Main()

 
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-02T10:27:19.0256774Z" />
    <EventRecordID>21170</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Serverdev.main.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Gordon.Wpf.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---&gt; Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---&gt; System.IO.FileNotFoundException: Impossibile trovare il file specificato. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.&lt;&gt;c__DisplayClass13_0.&lt;&lt;NavigateCore&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.&lt;&gt;c.&lt;.cctor&gt;b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Gordon.Wpf.App.Main()
</Data>
  </EventData>
</Event>
 
![thumbnail_image](https://github.com/user-attachments/assets/63a2cd84-c48b-4ff1-ba7e-6fad67c2506a)

**Comment by Stefano-Primo-EOS** [comment]
Gordon è meglio sia installato user-wide (dato che è un utente ad adoperarlo) 
Gordon Service invece è necessario installarlo machine-wide!

Per il problema di gordon che si chiude una volta aperto è dovuto a questo: 
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException

Alcuni server, non hanno installato di default la WebView. Per farlo basta installarlo: https://developer.microsoft.com/en-us/microsoft-edge/webview2/
